package com.tim10.glavna_knjiga.mappings;

// Generated May 22, 2015 3:37:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dokumenti generated by hbm2java
 */
@Entity
@Table(name = "Dokumenti", catalog = "Tim10")
public class Dokumenti implements java.io.Serializable {

	private DokumentiId id;
	private VrstaDokumenta vrstaDokumenta;
	private String naziv;
	private String opis;
	private Set<StavkeNaloga> stavkeNalogas = new HashSet<StavkeNaloga>(0);

	public Dokumenti() {
	}

	public Dokumenti(DokumentiId id, VrstaDokumenta vrstaDokumenta) {
		this.id = id;
		this.vrstaDokumenta = vrstaDokumenta;
	}

	public Dokumenti(DokumentiId id, VrstaDokumenta vrstaDokumenta,
			String naziv, String opis, Set<StavkeNaloga> stavkeNalogas) {
		this.id = id;
		this.vrstaDokumenta = vrstaDokumenta;
		this.naziv = naziv;
		this.opis = opis;
		this.stavkeNalogas = stavkeNalogas;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "vrstaDokumentaId", column = @Column(name = "VrstaDokumenta_Id", nullable = false)) })
	public DokumentiId getId() {
		return this.id;
	}

	public void setId(DokumentiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VrstaDokumenta_Id", nullable = false, insertable = false, updatable = false)
	public VrstaDokumenta getVrstaDokumenta() {
		return this.vrstaDokumenta;
	}

	public void setVrstaDokumenta(VrstaDokumenta vrstaDokumenta) {
		this.vrstaDokumenta = vrstaDokumenta;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "Opis", length = 45)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dokumenti")
	public Set<StavkeNaloga> getStavkeNalogas() {
		return this.stavkeNalogas;
	}

	public void setStavkeNalogas(Set<StavkeNaloga> stavkeNalogas) {
		this.stavkeNalogas = stavkeNalogas;
	}

}
