package com.tim10.glavna_knjiga.mappings;

// Generated May 24, 2015 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Klijent generated by hbm2java
 */
@Entity
@Table(name = "Klijent", catalog = "Tim10", uniqueConstraints = @UniqueConstraint(columnNames = "SifraKlijenta"))
public class Klijent implements java.io.Serializable {

	private int id;
	private String naziv;
	private String sifraKlijenta;
	private String opis;
	private String adresa;
	private String telefon;
	private String fax;
	private String tip;
	private Set<Preduzece> preduzeces = new HashSet<Preduzece>(0);
	private Set<StavkeNaloga> stavkeNalogas = new HashSet<StavkeNaloga>(0);

	public Klijent() {
	}

	public Klijent(int id) {
		this.id = id;
	}

	public Klijent(int id, String naziv, String sifraKlijenta, String opis,
			String adresa, String telefon, String fax, String tip,
			Set<Preduzece> preduzeces, Set<StavkeNaloga> stavkeNalogas) {
		this.id = id;
		this.naziv = naziv;
		this.sifraKlijenta = sifraKlijenta;
		this.opis = opis;
		this.adresa = adresa;
		this.telefon = telefon;
		this.fax = fax;
		this.tip = tip;
		this.preduzeces = preduzeces;
		this.stavkeNalogas = stavkeNalogas;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "SifraKlijenta", unique = true, length = 5)
	public String getSifraKlijenta() {
		return this.sifraKlijenta;
	}

	public void setSifraKlijenta(String sifraKlijenta) {
		this.sifraKlijenta = sifraKlijenta;
	}

	@Column(name = "Opis", length = 200)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@Column(name = "Adresa", length = 45)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "Telefon", length = 20)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Column(name = "Fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "Tip", length = 45)
	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Klijent_has_Preduzece", catalog = "Tim10", joinColumns = { @JoinColumn(name = "Klijent_Id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Preduzece_IdPreduzece", nullable = false, updatable = false) })
	public Set<Preduzece> getPreduzeces() {
		return this.preduzeces;
	}

	public void setPreduzeces(Set<Preduzece> preduzeces) {
		this.preduzeces = preduzeces;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klijent")
	public Set<StavkeNaloga> getStavkeNalogas() {
		return this.stavkeNalogas;
	}

	public void setStavkeNalogas(Set<StavkeNaloga> stavkeNalogas) {
		this.stavkeNalogas = stavkeNalogas;
	}

}
