package com.tim10.glavna_knjiga.mappings;

// Generated May 21, 2015 7:20:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KontniOkvir generated by hbm2java
 */
@Entity
@Table(name = "KontniOkvir", catalog = "Tim10")
public class KontniOkvir implements java.io.Serializable {

	private Integer id;
	private String brojKonta;
	private String naziv;

	public KontniOkvir() {
	}

	public KontniOkvir(String brojKonta, String naziv) {
		this.brojKonta = brojKonta;
		this.naziv = naziv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "BrojKonta", nullable = false, length = 16777215)
	public String getBrojKonta() {
		return this.brojKonta;
	}

	public void setBrojKonta(String brojKonta) {
		this.brojKonta = brojKonta;
	}

	@Column(name = "Naziv", nullable = false, length = 16777215)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

}
