package com.tim10.glavna_knjiga.mappings;

// Generated May 24, 2015 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KontniPlan generated by hbm2java
 */
@Entity
@Table(name = "KontniPlan", catalog = "Tim10")
public class KontniPlan implements java.io.Serializable {

	private int idKontniPlan;
	private Preduzece preduzece;
	private String naziv;
	private Date datumKreiranja;
	private Integer poslovnaGodina;
	private Set<KontniOkvir> kontniOkvirs = new HashSet<KontniOkvir>(0);

	public KontniPlan() {
	}

	public KontniPlan(int idKontniPlan, Preduzece preduzece) {
		this.idKontniPlan = idKontniPlan;
		this.preduzece = preduzece;
	}

	public KontniPlan(int idKontniPlan, Preduzece preduzece, String naziv,
			Date datumKreiranja, Integer poslovnaGodina,
			Set<KontniOkvir> kontniOkvirs) {
		this.idKontniPlan = idKontniPlan;
		this.preduzece = preduzece;
		this.naziv = naziv;
		this.datumKreiranja = datumKreiranja;
		this.poslovnaGodina = poslovnaGodina;
		this.kontniOkvirs = kontniOkvirs;
	}

	@Id
	@Column(name = "IdKontniPlan", unique = true, nullable = false)
	public int getIdKontniPlan() {
		return this.idKontniPlan;
	}

	public void setIdKontniPlan(int idKontniPlan) {
		this.idKontniPlan = idKontniPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Preduzece_IdPreduzece", nullable = false)
	public Preduzece getPreduzece() {
		return this.preduzece;
	}

	public void setPreduzece(Preduzece preduzece) {
		this.preduzece = preduzece;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatumKreiranja", length = 0)
	public Date getDatumKreiranja() {
		return this.datumKreiranja;
	}

	public void setDatumKreiranja(Date datumKreiranja) {
		this.datumKreiranja = datumKreiranja;
	}

	@Column(name = "PoslovnaGodina")
	public Integer getPoslovnaGodina() {
		return this.poslovnaGodina;
	}

	public void setPoslovnaGodina(Integer poslovnaGodina) {
		this.poslovnaGodina = poslovnaGodina;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "KontniPlan_has_KontniOkvir", catalog = "Tim10", joinColumns = { @JoinColumn(name = "KontniPlan_IdKontniPlan", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "KontniOkvir_Id", nullable = false, updatable = false) })
	public Set<KontniOkvir> getKontniOkvirs() {
		return this.kontniOkvirs;
	}

	public void setKontniOkvirs(Set<KontniOkvir> kontniOkvirs) {
		this.kontniOkvirs = kontniOkvirs;
	}

}
