package com.tim10.glavna_knjiga.mappings;

// Generated May 20, 2015 4:46:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * KontoTipovi generated by hbm2java
 */
@Entity
@Table(name = "KontoTipovi", catalog = "Tim10")
public class KontoTipovi implements java.io.Serializable {

	private int id;
	private String naziv;

	public KontoTipovi() {
	}

	public KontoTipovi(int id) {
		this.id = id;
	}

	public KontoTipovi(int id, String naziv) {
		this.id = id;
		this.naziv = naziv;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

}
