package com.tim10.glavna_knjiga.mappings;

// Generated May 20, 2015 4:46:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KontniPlan generated by hbm2java
 */
@Entity
@Table(name = "KontniPlan", catalog = "Tim10")
public class KontniPlan implements java.io.Serializable {

	private int idKontniPlan;
	private String naziv;
	private Date datumKreiranja;
	private Integer poslovnaGodina;

	public KontniPlan() {
	}

	public KontniPlan(int idKontniPlan) {
		this.idKontniPlan = idKontniPlan;
	}

	public KontniPlan(int idKontniPlan, String naziv, Date datumKreiranja,
			Integer poslovnaGodina) {
		this.idKontniPlan = idKontniPlan;
		this.naziv = naziv;
		this.datumKreiranja = datumKreiranja;
		this.poslovnaGodina = poslovnaGodina;
	}

	@Id
	@Column(name = "IdKontniPlan", unique = true, nullable = false)
	public int getIdKontniPlan() {
		return this.idKontniPlan;
	}

	public void setIdKontniPlan(int idKontniPlan) {
		this.idKontniPlan = idKontniPlan;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatumKreiranja", length = 0)
	public Date getDatumKreiranja() {
		return this.datumKreiranja;
	}

	public void setDatumKreiranja(Date datumKreiranja) {
		this.datumKreiranja = datumKreiranja;
	}

	@Column(name = "PoslovnaGodina")
	public Integer getPoslovnaGodina() {
		return this.poslovnaGodina;
	}

	public void setPoslovnaGodina(Integer poslovnaGodina) {
		this.poslovnaGodina = poslovnaGodina;
	}

}
