package com.tim10.glavna_knjiga.mappings;

// Generated May 24, 2015 3:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nalozi generated by hbm2java
 */
@Entity
@Table(name = "Nalozi", catalog = "Tim10", uniqueConstraints = @UniqueConstraint(columnNames = "SifraNaloga"))
public class Nalozi implements java.io.Serializable {

	private int id;
	private Korisnik korisnik;
	private Preduzece preduzece;
	private String naziv;
	private String sifraNaloga;
	private Integer status;
	private Date datumKnjizenja;
	private Date datumKreiranja;
	private Set<StavkeNaloga> stavkeNalogas = new HashSet<StavkeNaloga>(0);

	public Nalozi() {
	}

	public Nalozi(int id, Korisnik korisnik, Preduzece preduzece) {
		this.id = id;
		this.korisnik = korisnik;
		this.preduzece = preduzece;
	}

	public Nalozi(int id, Korisnik korisnik, Preduzece preduzece, String naziv,
			String sifraNaloga, Integer status, Date datumKnjizenja,
			Date datumKreiranja, Set<StavkeNaloga> stavkeNalogas) {
		this.id = id;
		this.korisnik = korisnik;
		this.preduzece = preduzece;
		this.naziv = naziv;
		this.sifraNaloga = sifraNaloga;
		this.status = status;
		this.datumKnjizenja = datumKnjizenja;
		this.datumKreiranja = datumKreiranja;
		this.stavkeNalogas = stavkeNalogas;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Korisnik_Id", nullable = false)
	public Korisnik getKorisnik() {
		return this.korisnik;
	}

	public void setKorisnik(Korisnik korisnik) {
		this.korisnik = korisnik;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Preduzece_IdPreduzece", nullable = false)
	public Preduzece getPreduzece() {
		return this.preduzece;
	}

	public void setPreduzece(Preduzece preduzece) {
		this.preduzece = preduzece;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "SifraNaloga", unique = true, length = 10)
	public String getSifraNaloga() {
		return this.sifraNaloga;
	}

	public void setSifraNaloga(String sifraNaloga) {
		this.sifraNaloga = sifraNaloga;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatumKnjizenja", length = 0)
	public Date getDatumKnjizenja() {
		return this.datumKnjizenja;
	}

	public void setDatumKnjizenja(Date datumKnjizenja) {
		this.datumKnjizenja = datumKnjizenja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatumKreiranja", length = 0)
	public Date getDatumKreiranja() {
		return this.datumKreiranja;
	}

	public void setDatumKreiranja(Date datumKreiranja) {
		this.datumKreiranja = datumKreiranja;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nalozi")
	public Set<StavkeNaloga> getStavkeNalogas() {
		return this.stavkeNalogas;
	}

	public void setStavkeNalogas(Set<StavkeNaloga> stavkeNalogas) {
		this.stavkeNalogas = stavkeNalogas;
	}

}
