package com.tim10.glavna_knjiga.mappings;

// Generated May 22, 2015 3:37:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nalozi generated by hbm2java
 */
@Entity
@Table(name = "Nalozi", catalog = "Tim10")
public class Nalozi implements java.io.Serializable {

	private int id;
	private Korisnik korisnik;
	private Preduzece preduzece;
	private Date datumKnjizenja;
	private Boolean status;
	private String nalozicol;
	private Set<StavkeNaloga> stavkeNalogas = new HashSet<StavkeNaloga>(0);

	public Nalozi() {
	}

	public Nalozi(int id, Korisnik korisnik, Preduzece preduzece) {
		this.id = id;
		this.korisnik = korisnik;
		this.preduzece = preduzece;
	}

	public Nalozi(int id, Korisnik korisnik, Preduzece preduzece,
			Date datumKnjizenja, Boolean status, String nalozicol,
			Set<StavkeNaloga> stavkeNalogas) {
		this.id = id;
		this.korisnik = korisnik;
		this.preduzece = preduzece;
		this.datumKnjizenja = datumKnjizenja;
		this.status = status;
		this.nalozicol = nalozicol;
		this.stavkeNalogas = stavkeNalogas;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Korisnik_Id", nullable = false)
	public Korisnik getKorisnik() {
		return this.korisnik;
	}

	public void setKorisnik(Korisnik korisnik) {
		this.korisnik = korisnik;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Preduzece_IdPreduzece", nullable = false)
	public Preduzece getPreduzece() {
		return this.preduzece;
	}

	public void setPreduzece(Preduzece preduzece) {
		this.preduzece = preduzece;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatumKnjizenja", length = 0)
	public Date getDatumKnjizenja() {
		return this.datumKnjizenja;
	}

	public void setDatumKnjizenja(Date datumKnjizenja) {
		this.datumKnjizenja = datumKnjizenja;
	}

	@Column(name = "Status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "Nalozicol", length = 45)
	public String getNalozicol() {
		return this.nalozicol;
	}

	public void setNalozicol(String nalozicol) {
		this.nalozicol = nalozicol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nalozi")
	public Set<StavkeNaloga> getStavkeNalogas() {
		return this.stavkeNalogas;
	}

	public void setStavkeNalogas(Set<StavkeNaloga> stavkeNalogas) {
		this.stavkeNalogas = stavkeNalogas;
	}

}
