package com.tim10.glavna_knjiga.mappings;

// Generated May 22, 2015 3:37:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Preduzece generated by hbm2java
 */
@Entity
@Table(name = "Preduzece", catalog = "Tim10")
public class Preduzece implements java.io.Serializable {

	private int idPreduzece;
	private String naziv;
	private String opis;
	private String adresa;
	private String telefon;
	private String fax;
	private Set<Nalozi> nalozis = new HashSet<Nalozi>(0);
	private Set<KontniPlan> kontniPlans = new HashSet<KontniPlan>(0);
	private Set<Klijent> klijents = new HashSet<Klijent>(0);

	public Preduzece() {
	}

	public Preduzece(int idPreduzece) {
		this.idPreduzece = idPreduzece;
	}

	public Preduzece(int idPreduzece, String naziv, String opis, String adresa,
			String telefon, String fax, Set<Nalozi> nalozis,
			Set<KontniPlan> kontniPlans, Set<Klijent> klijents) {
		this.idPreduzece = idPreduzece;
		this.naziv = naziv;
		this.opis = opis;
		this.adresa = adresa;
		this.telefon = telefon;
		this.fax = fax;
		this.nalozis = nalozis;
		this.kontniPlans = kontniPlans;
		this.klijents = klijents;
	}

	@Id
	@Column(name = "IdPreduzece", unique = true, nullable = false)
	public int getIdPreduzece() {
		return this.idPreduzece;
	}

	public void setIdPreduzece(int idPreduzece) {
		this.idPreduzece = idPreduzece;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "Opis", length = 45)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@Column(name = "Adresa", length = 45)
	public String getAdresa() {
		return this.adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	@Column(name = "Telefon", length = 20)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Column(name = "Fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzece")
	public Set<Nalozi> getNalozis() {
		return this.nalozis;
	}

	public void setNalozis(Set<Nalozi> nalozis) {
		this.nalozis = nalozis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preduzece")
	public Set<KontniPlan> getKontniPlans() {
		return this.kontniPlans;
	}

	public void setKontniPlans(Set<KontniPlan> kontniPlans) {
		this.kontniPlans = kontniPlans;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Klijent_has_Preduzece", catalog = "Tim10", joinColumns = { @JoinColumn(name = "Preduzece_IdPreduzece", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Klijent_Id", nullable = false, updatable = false) })
	public Set<Klijent> getKlijents() {
		return this.klijents;
	}

	public void setKlijents(Set<Klijent> klijents) {
		this.klijents = klijents;
	}

}
