package com.tim10.glavna_knjiga.mappings;

// Generated May 20, 2015 4:46:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StavkeNaloga generated by hbm2java
 */
@Entity
@Table(name = "StavkeNaloga", catalog = "Tim10")
public class StavkeNaloga implements java.io.Serializable {

	private int id;
	private String naziv;
	private Date datumKreiranja;
	private BigDecimal duguje;
	private BigDecimal potrazuje;

	public StavkeNaloga() {
	}

	public StavkeNaloga(int id) {
		this.id = id;
	}

	public StavkeNaloga(int id, String naziv, Date datumKreiranja,
			BigDecimal duguje, BigDecimal potrazuje) {
		this.id = id;
		this.naziv = naziv;
		this.datumKreiranja = datumKreiranja;
		this.duguje = duguje;
		this.potrazuje = potrazuje;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DatumKreiranja", length = 0)
	public Date getDatumKreiranja() {
		return this.datumKreiranja;
	}

	public void setDatumKreiranja(Date datumKreiranja) {
		this.datumKreiranja = datumKreiranja;
	}

	@Column(name = "Duguje", precision = 18)
	public BigDecimal getDuguje() {
		return this.duguje;
	}

	public void setDuguje(BigDecimal duguje) {
		this.duguje = duguje;
	}

	@Column(name = "Potrazuje", precision = 18)
	public BigDecimal getPotrazuje() {
		return this.potrazuje;
	}

	public void setPotrazuje(BigDecimal potrazuje) {
		this.potrazuje = potrazuje;
	}

}
