package com.tim10.glavna_knjiga.mappings;

// Generated May 20, 2015 4:46:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblStudenti generated by hbm2java
 */
@Entity
@Table(name = "tblStudenti", catalog = "Tim10")
public class TblStudenti implements java.io.Serializable {

	private int id;
	private TblOdsjeci tblOdsjeci;
	private String name;
	private String surname;

	public TblStudenti() {
	}

	public TblStudenti(int id, TblOdsjeci tblOdsjeci) {
		this.id = id;
		this.tblOdsjeci = tblOdsjeci;
	}

	public TblStudenti(int id, TblOdsjeci tblOdsjeci, String name,
			String surname) {
		this.id = id;
		this.tblOdsjeci = tblOdsjeci;
		this.name = name;
		this.surname = surname;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tblOdsjeci_id", nullable = false)
	public TblOdsjeci getTblOdsjeci() {
		return this.tblOdsjeci;
	}

	public void setTblOdsjeci(TblOdsjeci tblOdsjeci) {
		this.tblOdsjeci = tblOdsjeci;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 45)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

}
