package com.tim10.glavna_knjiga.mappings;

// Generated May 22, 2015 3:37:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VrstaDokumenta generated by hbm2java
 */
@Entity
@Table(name = "VrstaDokumenta", catalog = "Tim10")
public class VrstaDokumenta implements java.io.Serializable {

	private Integer id;
	private String naziv;
	private Set<Dokumenti> dokumentis = new HashSet<Dokumenti>(0);

	public VrstaDokumenta() {
	}

	public VrstaDokumenta(String naziv, Set<Dokumenti> dokumentis) {
		this.naziv = naziv;
		this.dokumentis = dokumentis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Naziv", length = 45)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vrstaDokumenta")
	public Set<Dokumenti> getDokumentis() {
		return this.dokumentis;
	}

	public void setDokumentis(Set<Dokumenti> dokumentis) {
		this.dokumentis = dokumentis;
	}

}
