/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tim10.glavna_knjiga.windows;

import com.tim10.glavna_knjiga.dbutils.NaloziUtils;
import com.tim10.glavna_knjiga.mappings.Nalozi;
import com.tim10.glavna_knjiga.mappings.StavkeNaloga;
import com.tim10.glavna_knjiga.session.UserData;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Omar
 */
public class Nalog extends javax.swing.JFrame {

    private JFrame _parent;
    private NaloziUtils _utils = NaloziUtils.getInstace();
    private Nalozi _nalog;
    private List<StavkeNaloga> _stavkeNaloga = new ArrayList<StavkeNaloga>();
    private List<StavkeNaloga> _obrisaneStavke = new ArrayList<StavkeNaloga>();
    /**
     * Creates new form Nalog
     */
    public Nalog() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        _nalog = new Nalozi();
    }
    
    public Nalog(HomeFrameRacunovodja parent) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        _nalog = new Nalozi(UserData.getKorisnik(), UserData.getPreduzece(), 0);
        _parent = parent;
        _stavkeNaloga.addAll(_nalog.getStavkeNalogas());
        
        recalculateFields();
        this.txtStatusNaloga.setText("NOVI");
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        this.txtDatumKreiranja.setText(dateFormat.format(_nalog.getDatumKreiranja()));
    }
    
    public Nalog(PregledNaloga parent, Nalozi nalog) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        _nalog = nalog;
        _parent = parent;
        _stavkeNaloga.addAll(_nalog.getStavkeNalogas());
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        this.txtNazivNaloga.setText(_nalog.getNaziv());
        this.txtSifraNaloga.setText(_nalog.getSifraNaloga());
        this.txtDatumKreiranja.setText(dateFormat.format(_nalog.getDatumKreiranja()));
        
        if (_nalog.getStatus() == 1)
        {
            this.txtStatusNaloga.setText("OTVOREN");
            
            this.txtSifraNaloga.setEditable(false);
            this.txtSifraNaloga.setBackground(Color.gray);
        }
        else
        {
            this.txtStatusNaloga.setText("UPISAN");
            this.txtDatumKnjizenja.setText((_nalog.getDatumKnjizenja() != null) ? dateFormat.format(_nalog.getDatumKnjizenja()) : "");
            
            disableForm();
        }
        
        updateTable();
        
        recalculateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNazivNaloga = new javax.swing.JTextField();
        txtDatumKreiranja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeNaloga = new javax.swing.JTable();
        btnZatvori = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStatusNaloga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDuguje = new javax.swing.JFormattedTextField();
        txtPotrazuje = new javax.swing.JFormattedTextField();
        txtSaldo = new javax.swing.JFormattedTextField();
        lbError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDatumKnjizenja = new javax.swing.JTextField();
        txtSifraNaloga = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbNaslov = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnUrediStavku = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSpasiNalog = new javax.swing.JButton();
        btnUpisiNalog = new javax.swing.JButton();
        btnObrisiNalog = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("SALDO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("POTRAŽUJE:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("STAVKE NALOGA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Naziv:");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 25));

        txtNazivNaloga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNazivNaloga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtNazivNaloga.setPreferredSize(new java.awt.Dimension(2, 25));

        txtDatumKreiranja.setEditable(false);
        txtDatumKreiranja.setBackground(new java.awt.Color(204, 204, 204));
        txtDatumKreiranja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDatumKreiranja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtDatumKreiranja.setFocusable(false);
        txtDatumKreiranja.setPreferredSize(new java.awt.Dimension(2, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Datum Knjiženja:");

        tblStavkeNaloga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Konto", "Naziv", "Dokument", "Datum Kreiranja", "Duguje", "Potražuje", "IdStavke"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStavkeNaloga.setFocusable(false);
        TableColumn idCol = tblStavkeNaloga.getColumnModel().getColumn(6);
        tblStavkeNaloga.getColumnModel().removeColumn(idCol);
        tblStavkeNaloga.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblStavkeNaloga.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStavkeNaloga);

        btnZatvori.setBackground(new java.awt.Color(51, 153, 255));
        btnZatvori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnZatvori.setForeground(new java.awt.Color(255, 255, 255));
        btnZatvori.setText("Zatvori");
        btnZatvori.setPreferredSize(new java.awt.Dimension(120, 25));
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Status:");

        txtStatusNaloga.setEditable(false);
        txtStatusNaloga.setBackground(new java.awt.Color(204, 204, 204));
        txtStatusNaloga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatusNaloga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtStatusNaloga.setFocusable(false);
        txtStatusNaloga.setPreferredSize(new java.awt.Dimension(2, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("DUGUJE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Šifra Naloga:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("KM");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("KM");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("KM");

        txtDuguje.setEditable(false);
        txtDuguje.setBackground(new java.awt.Color(204, 204, 204));
        txtDuguje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtDuguje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtDuguje.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDuguje.setToolTipText("");
        txtDuguje.setFocusable(false);
        txtDuguje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPotrazuje.setEditable(false);
        txtPotrazuje.setBackground(new java.awt.Color(204, 204, 204));
        txtPotrazuje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtPotrazuje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtPotrazuje.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPotrazuje.setToolTipText("");
        txtPotrazuje.setFocusable(false);
        txtPotrazuje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(204, 204, 204));
        txtSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSaldo.setToolTipText("");
        txtSaldo.setFocusable(false);
        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 51, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Datum Kreiranja:");

        txtDatumKnjizenja.setEditable(false);
        txtDatumKnjizenja.setBackground(new java.awt.Color(204, 204, 204));
        txtDatumKnjizenja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDatumKnjizenja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtDatumKnjizenja.setFocusable(false);
        txtDatumKnjizenja.setPreferredSize(new java.awt.Dimension(2, 25));

        txtSifraNaloga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSifraNaloga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtSifraNaloga.setPreferredSize(new java.awt.Dimension(2, 25));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        lbNaslov.setBackground(new java.awt.Color(51, 51, 255));
        lbNaslov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNaslov.setForeground(new java.awt.Color(255, 255, 255));
        lbNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNaslov.setText("NALOG");
        jPanel1.add(lbNaslov);
        lbNaslov.setBounds(310, 0, 157, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)), "Stavke", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        btnDodajStavku.setBackground(new java.awt.Color(51, 153, 255));
        btnDodajStavku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDodajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnDodajStavku.setText("Dodaj Stavku");
        btnDodajStavku.setPreferredSize(new java.awt.Dimension(120, 25));
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setBackground(new java.awt.Color(51, 153, 255));
        btnObrisiStavku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnObrisiStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisiStavku.setText("Obriši Stavku");
        btnObrisiStavku.setPreferredSize(new java.awt.Dimension(120, 25));
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        btnUrediStavku.setBackground(new java.awt.Color(51, 153, 255));
        btnUrediStavku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUrediStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnUrediStavku.setText("Uredi Stavku");
        btnUrediStavku.setPreferredSize(new java.awt.Dimension(120, 25));
        btnUrediStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrediStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiStavku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUrediStavku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnUrediStavku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)), "Nalog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(51, 153, 255))); // NOI18N

        btnSpasiNalog.setBackground(new java.awt.Color(51, 153, 255));
        btnSpasiNalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSpasiNalog.setForeground(new java.awt.Color(255, 255, 255));
        btnSpasiNalog.setText("Spasi Nalog");
        btnSpasiNalog.setPreferredSize(new java.awt.Dimension(120, 25));
        btnSpasiNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpasiNalogActionPerformed(evt);
            }
        });

        btnUpisiNalog.setBackground(new java.awt.Color(51, 153, 255));
        btnUpisiNalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpisiNalog.setForeground(new java.awt.Color(255, 255, 255));
        btnUpisiNalog.setText("Upiši Nalog");
        btnUpisiNalog.setPreferredSize(new java.awt.Dimension(120, 25));
        btnUpisiNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpisiNalogActionPerformed(evt);
            }
        });

        btnObrisiNalog.setBackground(new java.awt.Color(51, 153, 255));
        btnObrisiNalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnObrisiNalog.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisiNalog.setText("Obriši Nalog");
        btnObrisiNalog.setPreferredSize(new java.awt.Dimension(120, 25));
        btnObrisiNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiNalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnObrisiNalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSpasiNalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpisiNalog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSpasiNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnUpisiNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnObrisiNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtDuguje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtPotrazuje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNazivNaloga, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtSifraNaloga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStatusNaloga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatumKreiranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatumKnjizenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNazivNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSifraNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStatusNaloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txtDatumKreiranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(txtDatumKnjizenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(txtDuguje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPotrazuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">
    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        _parent.setEnabled(true);
        _parent.requestFocus();
    }//GEN-LAST:event_formWindowClosed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        
        clearError();
        
        _stavkeNaloga.add(new StavkeNaloga(_nalog));

        Stavka novaStavka = new Stavka(this, _stavkeNaloga.get(_stavkeNaloga.size() - 1), false);
        
        this.setEnabled(false);
        novaStavka.setVisible(true);
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        
        clearError();
        
        DefaultTableModel model = ((DefaultTableModel) this.tblStavkeNaloga.getModel());
        
        int selectedRow = this.tblStavkeNaloga.getSelectedRow();
        
        if (selectedRow != -1)
        {
            int stavkaId = (Integer)model.getValueAt(selectedRow, 6);
            
            if (stavkaId != -1)
            {
                _obrisaneStavke.add(_stavkeNaloga.get(selectedRow));
            }
            
            model.removeRow(this.tblStavkeNaloga.getSelectedRow());
            _stavkeNaloga.remove(selectedRow);
            
            recalculateFields();
        }
        else
        {
            if (this.tblStavkeNaloga.getRowCount() == 0)
                this.setErrorMsg("Nema unešenih stavki.");
            else
                this.setErrorMsg("Potrebno je selektovati stavku za brisanje.");
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnUrediStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrediStavkuActionPerformed
        
        clearError();
        
        DefaultTableModel model = ((DefaultTableModel) this.tblStavkeNaloga.getModel());
        
        int selectedRow = this.tblStavkeNaloga.getSelectedRow();
        
        if (selectedRow != -1)
        {
            StavkeNaloga stavka = _stavkeNaloga.get(selectedRow);
            
            Stavka editStavka = new Stavka(this, stavka, true);
            
            this.setEnabled(false);
            editStavka.setVisible(true);
        }
        else
        {
            if (this.tblStavkeNaloga.getRowCount() == 0)
                this.setErrorMsg("Nema unešenih stavki.");
            else
                this.setErrorMsg("Potrebno je selektovati stavku.");
        }
    }//GEN-LAST:event_btnUrediStavkuActionPerformed

    private void btnSpasiNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpasiNalogActionPerformed
        
        clearError();
        
        try
        {
            if (_nalog.getStatus() == 0)
            {
                if (this.txtNazivNaloga.getText().isEmpty() || this.txtSifraNaloga.getText().isEmpty())
                {
                    setErrorMsg("Potrebno unijeti sva polja.");

                    return;
                }

                _nalog.setNaziv(this.txtNazivNaloga.getText());
                _nalog.setSifraNaloga(this.txtSifraNaloga.getText());

                _utils.spasiNalog(_nalog, false);
                _utils.spasiStavkeNaloga(_stavkeNaloga, _nalog);

                JOptionPane.showMessageDialog(this, String.format("Nalog sa šifrom: %s uspješno spašen.", _nalog.getSifraNaloga()), null, JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }
            else
            {
                if (this.txtNazivNaloga.getText().isEmpty())
                {
                    setErrorMsg("Potrebno unijeti sva polja.");

                    return;
                }
                
                _nalog.setNaziv(this.txtNazivNaloga.getText());
                _utils.izmijeniNalog(_nalog, false);
                _utils.spasiStavkeNaloga(_stavkeNaloga, _nalog);
                _utils.obrisiStavkeNaloga(_obrisaneStavke);
                
                JOptionPane.showMessageDialog(this, String.format("Nalog sa šifrom: %s uspješno spašen.", _nalog.getSifraNaloga()), null, JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Greška prilikom spašavanja naloga. " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSpasiNalogActionPerformed

    private void btnObrisiNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiNalogActionPerformed
        clearError();
        
        try
        {
            if (_nalog.getStatus() == 0)
            {
                this.dispose();
                return;
            }

            _utils.obrisiNalog(_nalog);
            
            JOptionPane.showMessageDialog(this, String.format("Nalog sa šifrom: %s uspješno obrisan.", _nalog.getSifraNaloga()), null, JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Greška prilikom brisanja naloga.", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiNalogActionPerformed

    private void btnUpisiNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpisiNalogActionPerformed
        clearError();
        
        try
        {
            if (_nalog.getStatus() == 0)
            {
                if (!validateUpis())
                    return;

                _nalog.setNaziv(this.txtNazivNaloga.getText());
                _nalog.setSifraNaloga(this.txtSifraNaloga.getText());

                _utils.spasiNalog(_nalog, true);
                _utils.spasiStavkeNaloga(_stavkeNaloga, _nalog);

                JOptionPane.showMessageDialog(this, String.format("Nalog sa šifrom: %s uspješno zaključen.", _nalog.getSifraNaloga()), null, JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }
            else
            {
                if (!validateUpis())
                    return;
                
                _nalog.setNaziv(this.txtNazivNaloga.getText());
                _utils.izmijeniNalog(_nalog, true);
                _utils.spasiStavkeNaloga(_stavkeNaloga, _nalog);
                _utils.obrisiStavkeNaloga(_obrisaneStavke);
                
                JOptionPane.showMessageDialog(this, String.format("Nalog sa šifrom: %s uspješno zaključen.", _nalog.getSifraNaloga()), null, JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Greška prilikom zaključivanja naloga.", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpisiNalogActionPerformed
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Set">
    public void setBigTitle(String title) {
        this.lbNaslov.setText(title);
    }
    
    public void setErrorMsg(String errorMsg) {
        this.lbError.setText(errorMsg);
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Get">
    public String getSifraNaloga() {
        return this.txtSifraNaloga.getText();
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Helpers">
    public void setFocusOnDodajStavku() {
        this.btnDodajStavku.requestFocus();
    }
    
    public void clearError() {
        this.lbError.setText("");
    }
    
    private void recalculateFields() {
        DefaultTableModel model = ((DefaultTableModel) this.tblStavkeNaloga.getModel());
        Double duguje = 0.00, potrazuje = 0.00;
        
        if (model.getRowCount() != 0)
        {
            for (int i = 0; i < model.getRowCount(); i++)
            {
                duguje += Double.parseDouble(model.getValueAt(i, 4).toString().replace(",", ""));
                potrazuje += Double.parseDouble(model.getValueAt(i, 5).toString().replace(",", ""));
            }
        }
        
        this.txtDuguje.setValue(duguje);
        this.txtPotrazuje.setValue(potrazuje);
        this.txtSaldo.setValue(duguje - potrazuje);
    }
    
    private void disableForm(){
        this.txtNazivNaloga.setEditable(false);
        this.txtNazivNaloga.setBackground(Color.gray);
        this.txtSifraNaloga.setEditable(false);
        this.txtSifraNaloga.setBackground(Color.gray);
        this.btnDodajStavku.setEnabled(false);
        this.btnObrisiNalog.setEnabled(false);
        this.btnObrisiStavku.setEnabled(false);
        this.btnSpasiNalog.setEnabled(false);
        this.btnUpisiNalog.setEnabled(false);
        this.btnUrediStavku.setEnabled(false);
        this.tblStavkeNaloga.setEnabled(false);
    }
    
    private boolean validateUpis() {
        if (this.txtNazivNaloga.getText().isEmpty())
        {
            setErrorMsg("Potrebno unijeti sva polja.");

            return false;
        }

        if (this.tblStavkeNaloga.getRowCount() == 0)
        {
            setErrorMsg("Nalog nema stavki za knjiženje.");

            return false;
        }

        if (Double.parseDouble(this.txtSaldo.getText().replace(",", "")) != 0)
        {
            setErrorMsg("Ukupno dugovanje mora biti jednako ukupnom potraživanju.");

            return false;
        }
        
        return true;
    }
            
// </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Table Helpers">
    public void addDataRow(Object[] rowData) {
        DefaultTableModel model = ((DefaultTableModel) this.tblStavkeNaloga.getModel());
        
        model.addRow(rowData);
        
        recalculateFields();
    }
    
    public void updateDataRow(Object[] rowData) {
        DefaultTableModel model = ((DefaultTableModel) this.tblStavkeNaloga.getModel());
        int selectedRow = this.tblStavkeNaloga.getSelectedRow();
        
        model.setValueAt(rowData[0], selectedRow, 0);
        model.setValueAt(rowData[1], selectedRow, 1);
        model.setValueAt(rowData[2], selectedRow, 2);
        model.setValueAt(rowData[3], selectedRow, 3);
        model.setValueAt(rowData[4], selectedRow, 4);
        model.setValueAt(rowData[5], selectedRow, 5);
        
        recalculateFields();
    }
    
    public int getSelectedRow() {
        return this.tblStavkeNaloga.getSelectedRow();
    }
    
    public void updateTable() {
        DefaultTableModel model = ((DefaultTableModel) this.tblStavkeNaloga.getModel());
        
        model.setRowCount(0);
        Object[] dataRow;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        for(StavkeNaloga stavka: _nalog.getStavkeNalogas())
        {
            dataRow = new Object[]{
                stavka.getKontniOkvir().getBrojKonta(),
                stavka.getNaziv(),
                stavka.getDokumenti().getNaziv(),
                dateFormat.format(stavka.getDatumKreiranja()),
                stavka.getDuguje(),
                stavka.getPotrazuje(),
                stavka.getId()};
            
            model.addRow(dataRow);
        }    
    }
    // </editor-fold>

  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nalog().setVisible(true);
            }
        });
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiNalog;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnSpasiNalog;
    private javax.swing.JButton btnUpisiNalog;
    private javax.swing.JButton btnUrediStavku;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbNaslov;
    private javax.swing.JTable tblStavkeNaloga;
    private javax.swing.JTextField txtDatumKnjizenja;
    private javax.swing.JTextField txtDatumKreiranja;
    private javax.swing.JFormattedTextField txtDuguje;
    private javax.swing.JTextField txtNazivNaloga;
    private javax.swing.JFormattedTextField txtPotrazuje;
    private javax.swing.JFormattedTextField txtSaldo;
    private javax.swing.JTextField txtSifraNaloga;
    private javax.swing.JTextField txtStatusNaloga;
    // End of variables declaration//GEN-END:variables
}
