/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tim10.glavna_knjiga.windows;

import com.tim10.glavna_knjiga.dbutils.NaloziUtils;
import com.tim10.glavna_knjiga.mappings.Nalozi;
import com.tim10.glavna_knjiga.mappings.Preduzece;
import com.tim10.glavna_knjiga.session.UserData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Omar
 */
public class PregledNaloga extends javax.swing.JFrame {

    private HomeFrameRacunovodja _parent;
    private List<Nalozi> _nalozi = new ArrayList<Nalozi>();
    private Preduzece _preduzece = UserData.getPreduzece();
    private NaloziUtils _utils = NaloziUtils.getInstace();        
    
    /**
     * Creates new form PregledNaloga
     */
    public PregledNaloga() {
        initComponents();
    }
    
     public PregledNaloga(HomeFrameRacunovodja parent) {
        initComponents();
        
        _parent = parent;
        setNazivPreduzeca();
        
        getNalozi(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPreduzece = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNalozi = new javax.swing.JTable();
        btnZatvori = new javax.swing.JButton();
        btnOtvoriNalog = new javax.swing.JButton();
        btnIzbrišiNalog = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFilterSifra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFilterNaziv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbFilterStatus = new javax.swing.JComboBox();
        lbErrorMsg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(758, 646));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("NALOZI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PREDUZEĆE:");

        lbPreduzece.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPreduzece.setForeground(new java.awt.Color(102, 102, 102));
        lbPreduzece.setText("Preduzece");

        tblNalozi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdNaloga", "Šifra Naloga", "Naziv", "Status", "Datum Kreiranja", "Datum Knjiženja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNalozi.setFocusable(false);
        TableColumn idCol = tblNalozi.getColumnModel().getColumn(0);
        tblNalozi.getColumnModel().removeColumn(idCol);
        jScrollPane1.setViewportView(tblNalozi);

        btnZatvori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        btnOtvoriNalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOtvoriNalog.setText("Otvori Nalog");
        btnOtvoriNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtvoriNalogActionPerformed(evt);
            }
        });

        btnIzbrišiNalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIzbrišiNalog.setText("Izbriši Nalog");
        btnIzbrišiNalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrišiNalogActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Šifra Naloga:");

        txtFilterSifra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFilterSifra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Naziv Naloga:");

        txtFilterNaziv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFilterNaziv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Status:");

        cbFilterStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbFilterStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SVI", "OTVOREN", "UPISAN" }));

        lbErrorMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbErrorMsg.setForeground(new java.awt.Color(255, 51, 51));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Traži");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPreduzece))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1)))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOtvoriNalog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzbrišiNalog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZatvori)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbErrorMsg, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFilterSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFilterNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbPreduzece))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFilterSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFilterNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbFilterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZatvori)
                    .addComponent(btnOtvoriNalog)
                    .addComponent(btnIzbrišiNalog))
                .addGap(28, 28, 28))
        );

        setSize(new java.awt.Dimension(794, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        _parent.setEnabled(true);
        _parent.requestFocus();
    }//GEN-LAST:event_formWindowClosed

    private void btnIzbrišiNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrišiNalogActionPerformed

        clearErrorMsg();
                
        int selectedRow = this.tblNalozi.getSelectedRow();
        DefaultTableModel model = ((DefaultTableModel) this.tblNalozi.getModel());
        
        if (selectedRow == -1)
        {
            setErrorMsg("Potrebno je selektovati nalog za brisanje.");
            
            return;
        }
        
        if (model.getValueAt(selectedRow, 3).toString().equals("UPISAN"))
        {
            setErrorMsg("Nije moguće obrisati upisan nalog.");
            
            return;
        }
        
        int idNalogaZaBrisanje = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
        for (Nalozi delNalog: _nalozi)
        {
            if (delNalog.getId() == idNalogaZaBrisanje)
            {
                _utils.obrisiNalog(delNalog);
                
                model.removeRow(selectedRow);
                
                JOptionPane.showMessageDialog(this, String.format("Nalog sa šifrom: %s uspješno obrisan.", delNalog.getSifraNaloga()), null, JOptionPane.INFORMATION_MESSAGE);
                
                break;
            }
        }
    }//GEN-LAST:event_btnIzbrišiNalogActionPerformed

    private void btnOtvoriNalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtvoriNalogActionPerformed
        clearErrorMsg();
                
        int selectedRow = this.tblNalozi.getSelectedRow();
        DefaultTableModel model = ((DefaultTableModel) this.tblNalozi.getModel());
        
        if (selectedRow == -1)
        {
            setErrorMsg("Potrebno je selektovati nalog.");
            
            return;
        }
        
        int idNaloga = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
        
        for (Nalozi nalog: _nalozi)
        {
            if (nalog.getId() == idNaloga)
            {
                this.setEnabled(false);
                
                Nalog nalogFrame = new Nalog(this, nalog);
                nalogFrame.setVisible(true);
                
                break;
            }
        }
    }//GEN-LAST:event_btnOtvoriNalogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearErrorMsg();
        
        getNalozi(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getNalozi(boolean isInit) {
        _nalozi = _utils.getNalozi(this.txtFilterSifra.getText(), this.txtFilterNaziv.getText(), this.cbFilterStatus.getSelectedIndex(), isInit);
        
        if (_nalozi.size() > 0)
        {
            updateTable(_nalozi);
        }
        else
        {
            ((DefaultTableModel) this.tblNalozi.getModel()).setRowCount(0);
        }
    }
    
    private void updateTable(List<Nalozi> nalozi) {
        
        DefaultTableModel model = ((DefaultTableModel) this.tblNalozi.getModel());
        
        model.setRowCount(0);
        Object[] dataRow;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        for(Nalozi nalog: nalozi)
        {
            dataRow = new Object[]{
                nalog.getId(),
                nalog.getSifraNaloga(),
                nalog.getNaziv(),
                (nalog.getStatus() == 1) ? "OTVOREN" : "UPISAN",
                dateFormat.format(nalog.getDatumKreiranja()),
                (nalog.getDatumKnjizenja() != null) ? dateFormat.format(nalog.getDatumKnjizenja()) : ""
            };
            
            model.addRow(dataRow);
        }
    }
    
    private void setNazivPreduzeca() {
        this.lbPreduzece.setText(_preduzece.getNaziv());
    }
    
    public void setErrorMsg(String errorMsg) {
        this.lbErrorMsg.setText(errorMsg);
    }
    
    public void clearErrorMsg() {
        this.lbErrorMsg.setText("");
    }
    
    public void refreshData()
    {
        getNalozi(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledNaloga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledNaloga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledNaloga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledNaloga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledNaloga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbrišiNalog;
    private javax.swing.JButton btnOtvoriNalog;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JComboBox cbFilterStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbErrorMsg;
    private javax.swing.JLabel lbPreduzece;
    private javax.swing.JTable tblNalozi;
    private javax.swing.JTextField txtFilterNaziv;
    private javax.swing.JTextField txtFilterSifra;
    // End of variables declaration//GEN-END:variables
}
